
language: node_js

node_js:
- node

git:
  depth: 1

script:
- parcel build --public-url=./ src/index.html src/embed.html

before_install:
- openssl aes-256-cbc -K $encrypted_0e4f6f173f5d_key -iv $encrypted_0e4f6f173f5d_iv -in deploy/deploy_rsa.enc -out deploy/deploy_rsa -d
- chmod 600 deploy/deploy_rsa

addons:
  ssh_known_hosts: foxcraft.dreamhost.com

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -e "ssh -i deploy/deploy_rsa" -ar --quiet --delete-after --exclude=data/ $TRAVIS_BUILD_DIR/dist/ gznoclip@foxcraft.dreamhost.com:noclip.website/
    on:
      branch: master
