
language: node_js

node_js:
- node

depth: 1

script:
- parcel build --public-url=./ src/index.html src/embed.html
- rm -f dist/data
- mv data/ dist/

before_install:
- openssl aes-256-cbc -K $encrypted_0e4f6f173f5d_key -iv $encrypted_0e4f6f173f5d_iv -in deploy/deploy_rsa.enc -out deploy/deploy_rsa -d

deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    local_dir: dist
    github_token: $GITHUB_TOKEN

  - provider: script
    skip_cleanup: true
    script: rsync -i deploy/deploy_rsa -ar --quiet $TRAVIS_BUILD_DIR/dist/ baptistchurch@foxcraft.dreamhost.com:noclip.website/
    on:
      branch: master
