
language: node_js
node_js:
  - "node"

script:
  - parcel build --public-url=./ index.html
  - parcel build --public-url=./ embed.html
  - rm -f dist/data
  - mv data/ dist/

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: parcel
