
language: node_js
node_js:
  - "node"

script:
  - parcel build index.html
  - mv data/ dist/

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
