
language: node_js
node_js:
  - "node"

depth: 1

script:
  - parcel build --public-url=./ src/index.html src/embed.hmtl
  - rm -f dist/data
  - mv data/ dist/

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
